export const NavLinks = [
  { link: "#about", value: "About" },
  { link: "#work", value: "Work" },
  { link: "#projects", value: "Projects" },
  { link: "#contact", value: "Contact Me" },
];

export const ExperienceList = [
  {
    company: "Bits of Good",
    role: "Software Developer",
    timeline: "Sep 2023 - Present",
    bullets: [
      "Saved founders 10 hours weekly by implementing calendar and event tracking features",
      "Collaborated with a cross-functional team using agile methodologies to develop full stack features in Next.js, tRPC, MongoDB, and Tailwind CSS",
    ],
    location: "Atlanta, GA",
  },
  {
    company: "Probity",
    role: "Software Engineering Intern",
    timeline: "May 2023 - Aug 2023",
    bullets: [
      "Saved recruiters 30+ hours per week and reducing staffing needs",
      "Engineered and trained a Python-based NLP model with 95% accuracy to extract skills from job listings",
      "Created 3 REST APIs in Flask to support user authentication, process SQL queries, and create email notifications",
      "Created a user-friendly dashboard using React.js, SQL, and Flask for seamless applicant scoring on jobs",
      "Saved employees 5 hours every month by adding automated backup systems and continuous model updates",
    ],
    location: "Herndon, VA",
  },
  {
    company: "Runway",
    role: "CTO and Co Founder",
    timeline: "Jun 2022 - Present",
    bullets: [
      "Led team in generating over $100k worth of revenue and engaging with over 2,000 total students and businesses",
      "Increased business retention by 50% by implementing candidate recommendations and candidate vetting systems",
      "Improved student engagement by 40% through message notification systems with Twilio’s SMS services",
      "Incorporated 10+ AWS features to streamline backend and storage processes",
      "Developed 10 REST APIs in Node.js for a job board, customer profiles, interviews, and SMS/email notifications",
      "Built end-to-end features using Figma, React.js, Next.js, Node.js, Tailwind CSS, FastAPI, Redis, and MongoDB",
    ],
    location: "Atlanta, GA",
  },
];

export const ProjectList = [
  {
    name: "Formulytics",
    skills: [
      "Javascript",
      "Node.js",
      "React.js",
      "Bootstrap",
      "AWS EC2",
      "Twilio Studio",
      "MongoDB",
      "Git",
      "Python",
    ],
    timeline: "Feb 2023",
    text: "A formula one racing visualization dashboard for viewers to get realtime depictions of driver positions and lap times.",
    url: "https://github.com/thearyanmittal/formulytics",
  },
  {
    name: "Runway Site",
    skills: [
      "React.js",
      "Next.js",
      "Tailwind CSS",
      "Node.js",
      "Amazon EC2",
      "Amazon S3",
      "Amazon DynamoDB",
      "Amazon API Gateway",
      "Amazon Cloudfront",
      "MongoDB",
      "Git",
      "Flask",
      "Java Spring",
    ],
    timeline: "Jan 2023 - Present",
    text: "Runway's website that allows students/businesses to sign up. It gives students access to job boards and businesses access to post their own jobs.",
    url: "https://www.joinrunway.io",
  },
  {
    name: "Sellraze Mobile App",
    skills: [
      "Typescript",
      "React Native",
      "Tailwind CSS",
      "Redux",
      "Google Firebase",
      "Git",
    ],
    timeline: "Dec 2023 - Jan 2024",
    text: "A mobile app for customers to scan/list products on the platform and access dashboard analytics.",
    url: "https://www.sellraze.com",
  },
  {
    name: "Web3 ATL NFT Dashboard",
    skills: [
      "Javascript",
      "Google Firebase",
      "React.js",
      "Svelte.js",
      "Bootstrap",
      "Metamask API",
      "Git",
    ],
    timeline: "February 2023 - March 2023",
    text: "A NFT Dashboard for attendees to claim personalized NFTs based on the role they played at the Web3 ATL conference.",
    url: "https://nft.web3atl.io/",
  },
];
