// export const NavLinks = [
//   { link: "#about", value: "About" },
//   { link: "#work", value: "Work" },
//   { link: "#projects", value: "Projects" },
//   { link: "#contact", value: "Contact Me" },
// ];

export const ExperienceList = [
  {
    company: "Overlap (YC S24)",
    url: "https://www.joinoverlap.com",
    role: "Software Engineer",
    timeline: "Sep 2024 - Present",
    bullets: ["Work in progress..."],
    location: "Remote",
  },
  {
    company: "AWS",
    url: "https://aws.amazon.com",
    role: "Software Dev Engineer Intern",
    timeline: "May 2024 - Aug 2024",
    bullets: [
      "Developed a custom LLM model integrated with Retrieval-Augmented Generation (RAG) and agent-based solutions, reducing developer debugging time by over 10 hours per instance",
      "Designed and implemented RAG infrastructure using team-specific code repositories, achieving a 93% accuracy",
      "Built automated ingestion and CDK deployment strategies to save 70+ engineers 2 hours every week",
      "Skills: Typescript, Python, React.js, Tailwind CSS, Langchain, AWS, Pinecone, Cypress, AWS CDK, Selenium",
    ],
    location: "Seattle, WA",
  },
  {
    company: "Runway",
    url: "https://www.joinrunway.io",
    role: "CTO and Co Founder",
    timeline: "Jun 2022 - Present",
    bullets: [
      "Built platform connecting early-stage startups with college students for freelance work, securing a $5M valuation and engaging over 2,000 students and businesses",
      "Increased business retention by 50% by implementing candidate recommendations and candidate vetting systems",
      "Improved student engagement by 40% through message notification systems with Twilio’s SMS services",
      "Incorporated 10+ AWS, GCP, and Azure features to streamline backend and storage processes",
      "Developed 10 REST APIs in Node.js for a job board, customer profiles, interviews, and SMS/email notifications",
      "Skills: Typescript, React.js, Next.js, Node.js, Express.js, Tailwind CSS, Redis, FastAPI, MongoDB, Langchain",
    ],
    location: "Atlanta, GA",
  },
  {
    company: "Probity",
    url: "https://probity.com",
    role: "Software Engineering Intern",
    timeline: "May 2023 - Aug 2023",
    bullets: [
      "Developed resume-vetting platform that streamlined the recruitment process, reducing manual effort by 30+ hours per week for recruiters and reduced staffing needs",
      "Engineered and trained a Python-based NLP model with 95% accuracy to extract skills from job listings",
      "Saved employees 5 hours every month by adding automated backup systems and continuous model updates",
      "Skills: Javascript, Python, React.js, Flask, SQLite, Tailwind CSS, Spacy, Numpy",
    ],
    location: "Herndon, VA",
  },
  {
    company: "Bits of Good",
    url: "https://bitsofgood.org",
    role: "Software Developer",
    timeline: "Sep 2023 - Present",
    bullets: [
      "Collaborated with a team to develop a non profit’s website, saving non-profit founders 10 hours weekly by implementing calendar and event tracking features",
      "Built centralized authentication and email micro-services used by 10+ teams using gRPC and Protobuf",
      "Skills: Next.js, tRPC, MongoDB, Prisma, Tailwind CSS, gRPC, Nest.js, Jest, Protobuf, PostgreSQL, Docker",
    ],
    location: "Atlanta, GA",
  },
];

export const ProjectList = [
  {
    name: "Formulytics",
    skills: [
      "Javascript",
      "Node.js",
      "React.js",
      "Bootstrap",
      "AWS EC2",
      "Twilio Studio",
      "MongoDB",
      "Git",
      "Python",
    ],
    timeline: "Feb 2023",
    text: "A formula one racing visualization dashboard for viewers to get realtime depictions of driver positions and lap times.",
    url: "https://devpost.com/software/formulytics",
  },
  {
    name: "Subtext",
    skills: [
      "Typescript",
      "React.js",
      "Chakra UI",
      "Flask",
      "Postman",
      "Hume API",
      "Git",
    ],
    timeline: "Feb 2024",
    text: "A full stack web app that provides a visual representation of tone, catering to both deaf and tone-deaf individuals, on any video.",
    url: "https://devpost.com/software/subtext",
  },
  {
    name: "Sellraze Mobile App",
    skills: [
      "Typescript",
      "React Native",
      "Tailwind CSS",
      "Redux",
      "Google Firebase",
      "Git",
    ],
    timeline: "Dec 2023 - Jan 2024",
    text: "A mobile app for customers to scan/list products on the platform and access dashboard analytics.",
    url: "https://www.sellraze.com",
  },
  {
    name: "Web3 ATL NFT Dashboard",
    skills: [
      "Javascript",
      "Google Firebase",
      "React.js",
      "Svelte.js",
      "Bootstrap",
      "Metamask API",
      "Git",
    ],
    timeline: "February 2023 - March 2023",
    text: "A NFT Dashboard for attendees to claim personalized NFTs based on the role they played at the Web3 ATL conference.",
    url: "https://nft.web3atl.io/",
  },
];
